### ISSUE TITLE
xml2stm.py

### ISSUE THREAD

**Issue by sameerkhurana10** [Qatar-Computing-Research-Institute/ArabicASRChallenge2016#2]
The script currently throws an error, when generating the 'stm' file which is used as the reference file while scoring using sclite.

The script is called from kaldi recipe/local/mgb_data_prep.sh. The error is due to the following line in xml2stm.py:
`tokens = [e.childNodes[0].data for e in segment.getElementsByTagName('element')]`

The line throws an exception when the element tag in the dev xml transcript is empty. For e.g.
`<element id="5331FFF2_358E_445E_BA71_74B745387304_w1824_manual" type="word"/>`
The xml file is at: `emacs /data/sls/scratch/sameerk/mgb_arabic_data/xml/5331FFF2-358E-445E-BA71-74B745387304.xml`

There are two fixes:
1. Handle this while generating the dev xmls
   Required Effort: Just a one line of code. I have already tested the change.
   Downside: We would need to generate the dev xmls again and upload to ftp server
2. Put a check in the xml2stm.py script
   Required Effort: Just have to put a condition to check for the empty string

@amali @yifan what do you guys think?

**Comment by yifan** [comment]
The empty element is there because of following: @hmubarak can you confirm this is okay)

<element id="5331FFF2_358E_445E_BA71_74B745387304_w1826_manual" type="word">لا/element
this is the utf8 xml
now this character لا
is replaced by ""
word.replaceAll("ﻷ", "");

**Comment by bouchakour16** [comment]
hello my dear friends
I am trying to use KLDI with MGB
May I find proleme Usage: $ wav-dir xml-dir sea-salt 
what do the words mean  wav-dir xml-dir sea-salt
