### ISSUE TITLE
Fix SCLITE scoring issue

### ISSUE THREAD

**Issue by sameerkhurana10** [Qatar-Computing-Research-Institute/ArabicASRChallenge2016#6]
Currently, we have a problem with sclite scoring option in the score.sh. The ctm file is not ordered properly.

**Comment by yshalabi** [comment]
I think this might be what I am currently debugging. 

Is the error you are seeing :  **"Error, Hypothesis file 'exp/mer80/tri2/decode/score_25/test_mer80.ctm.updated' does not exist"**

**Comment by sameerkhurana10** [comment]
No, that is not the problem.

Can you use the basic scoring instead of sclite scoring for now.

look at the gale_arabic recipe: local/score.sh and use the compute-wer
method to get the WER.

I will push the fix for the SCLITE scoring soon.

Thanks
S

On Wed, Mar 16, 2016 at 7:33 PM, Yasser Shalabi notifications@github.com
wrote:

> I think this might be what I am currently debugging.
> 
> Is the error you are seeing : _"Error, Hypothesis file
> 'exp/mer80/tri2/decode/score_25/test_mer80.ctm.updated' does not exist"_
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/Qatar-Computing-Research-Institute/ArabicASRChallenge2016/issues/6#issuecomment-197412729

## 

conversation enriches understanding, but solitude is the school of genius.
